# CMake generated Testfile for 
# Source directory: E:/Code/PotatoStandardLibrary/Test
# Build directory: E:/Code/PotatoStandardLibrary/build_bench_timing/Test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(BufferTest_cpp "E:/Code/PotatoStandardLibrary/build_bench_timing/Test/Debug/BufferTest_cpp.exe")
  set_tests_properties(BufferTest_cpp PROPERTIES  _BACKTRACE_TRIPLES "E:/Code/PotatoStandardLibrary/Test/CMakeLists.txt;22;add_test;E:/Code/PotatoStandardLibrary/Test/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(BufferTest_cpp "E:/Code/PotatoStandardLibrary/build_bench_timing/Test/Release/BufferTest_cpp.exe")
  set_tests_properties(BufferTest_cpp PROPERTIES  _BACKTRACE_TRIPLES "E:/Code/PotatoStandardLibrary/Test/CMakeLists.txt;22;add_test;E:/Code/PotatoStandardLibrary/Test/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(BufferTest_cpp "E:/Code/PotatoStandardLibrary/build_bench_timing/Test/MinSizeRel/BufferTest_cpp.exe")
  set_tests_properties(BufferTest_cpp PROPERTIES  _BACKTRACE_TRIPLES "E:/Code/PotatoStandardLibrary/Test/CMakeLists.txt;22;add_test;E:/Code/PotatoStandardLibrary/Test/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(BufferTest_cpp "E:/Code/PotatoStandardLibrary/build_bench_timing/Test/RelWithDebInfo/BufferTest_cpp.exe")
  set_tests_properties(BufferTest_cpp PROPERTIES  _BACKTRACE_TRIPLES "E:/Code/PotatoStandardLibrary/Test/CMakeLists.txt;22;add_test;E:/Code/PotatoStandardLibrary/Test/CMakeLists.txt;0;")
else()
  add_test(BufferTest_cpp NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(LoggerTest_cpp "E:/Code/PotatoStandardLibrary/build_bench_timing/Test/Debug/LoggerTest_cpp.exe")
  set_tests_properties(LoggerTest_cpp PROPERTIES  _BACKTRACE_TRIPLES "E:/Code/PotatoStandardLibrary/Test/CMakeLists.txt;22;add_test;E:/Code/PotatoStandardLibrary/Test/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(LoggerTest_cpp "E:/Code/PotatoStandardLibrary/build_bench_timing/Test/Release/LoggerTest_cpp.exe")
  set_tests_properties(LoggerTest_cpp PROPERTIES  _BACKTRACE_TRIPLES "E:/Code/PotatoStandardLibrary/Test/CMakeLists.txt;22;add_test;E:/Code/PotatoStandardLibrary/Test/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(LoggerTest_cpp "E:/Code/PotatoStandardLibrary/build_bench_timing/Test/MinSizeRel/LoggerTest_cpp.exe")
  set_tests_properties(LoggerTest_cpp PROPERTIES  _BACKTRACE_TRIPLES "E:/Code/PotatoStandardLibrary/Test/CMakeLists.txt;22;add_test;E:/Code/PotatoStandardLibrary/Test/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(LoggerTest_cpp "E:/Code/PotatoStandardLibrary/build_bench_timing/Test/RelWithDebInfo/LoggerTest_cpp.exe")
  set_tests_properties(LoggerTest_cpp PROPERTIES  _BACKTRACE_TRIPLES "E:/Code/PotatoStandardLibrary/Test/CMakeLists.txt;22;add_test;E:/Code/PotatoStandardLibrary/Test/CMakeLists.txt;0;")
else()
  add_test(LoggerTest_cpp NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(MemoryAllocatorTest_cpp "E:/Code/PotatoStandardLibrary/build_bench_timing/Test/Debug/MemoryAllocatorTest_cpp.exe")
  set_tests_properties(MemoryAllocatorTest_cpp PROPERTIES  _BACKTRACE_TRIPLES "E:/Code/PotatoStandardLibrary/Test/CMakeLists.txt;22;add_test;E:/Code/PotatoStandardLibrary/Test/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(MemoryAllocatorTest_cpp "E:/Code/PotatoStandardLibrary/build_bench_timing/Test/Release/MemoryAllocatorTest_cpp.exe")
  set_tests_properties(MemoryAllocatorTest_cpp PROPERTIES  _BACKTRACE_TRIPLES "E:/Code/PotatoStandardLibrary/Test/CMakeLists.txt;22;add_test;E:/Code/PotatoStandardLibrary/Test/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(MemoryAllocatorTest_cpp "E:/Code/PotatoStandardLibrary/build_bench_timing/Test/MinSizeRel/MemoryAllocatorTest_cpp.exe")
  set_tests_properties(MemoryAllocatorTest_cpp PROPERTIES  _BACKTRACE_TRIPLES "E:/Code/PotatoStandardLibrary/Test/CMakeLists.txt;22;add_test;E:/Code/PotatoStandardLibrary/Test/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(MemoryAllocatorTest_cpp "E:/Code/PotatoStandardLibrary/build_bench_timing/Test/RelWithDebInfo/MemoryAllocatorTest_cpp.exe")
  set_tests_properties(MemoryAllocatorTest_cpp PROPERTIES  _BACKTRACE_TRIPLES "E:/Code/PotatoStandardLibrary/Test/CMakeLists.txt;22;add_test;E:/Code/PotatoStandardLibrary/Test/CMakeLists.txt;0;")
else()
  add_test(MemoryAllocatorTest_cpp NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(ObservableTest_cpp "E:/Code/PotatoStandardLibrary/build_bench_timing/Test/Debug/ObservableTest_cpp.exe")
  set_tests_properties(ObservableTest_cpp PROPERTIES  _BACKTRACE_TRIPLES "E:/Code/PotatoStandardLibrary/Test/CMakeLists.txt;22;add_test;E:/Code/PotatoStandardLibrary/Test/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(ObservableTest_cpp "E:/Code/PotatoStandardLibrary/build_bench_timing/Test/Release/ObservableTest_cpp.exe")
  set_tests_properties(ObservableTest_cpp PROPERTIES  _BACKTRACE_TRIPLES "E:/Code/PotatoStandardLibrary/Test/CMakeLists.txt;22;add_test;E:/Code/PotatoStandardLibrary/Test/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(ObservableTest_cpp "E:/Code/PotatoStandardLibrary/build_bench_timing/Test/MinSizeRel/ObservableTest_cpp.exe")
  set_tests_properties(ObservableTest_cpp PROPERTIES  _BACKTRACE_TRIPLES "E:/Code/PotatoStandardLibrary/Test/CMakeLists.txt;22;add_test;E:/Code/PotatoStandardLibrary/Test/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(ObservableTest_cpp "E:/Code/PotatoStandardLibrary/build_bench_timing/Test/RelWithDebInfo/ObservableTest_cpp.exe")
  set_tests_properties(ObservableTest_cpp PROPERTIES  _BACKTRACE_TRIPLES "E:/Code/PotatoStandardLibrary/Test/CMakeLists.txt;22;add_test;E:/Code/PotatoStandardLibrary/Test/CMakeLists.txt;0;")
else()
  add_test(ObservableTest_cpp NOT_AVAILABLE)
endif()
